[package]
name = "ntoseye-py"
version.workspace = true
edition = "2024"
authors = [ "dmaivel" ]
description = "Python SDK for the ntoseye Windows kernel debugger"
license = "MIT"
publish = false

[lib]
name = "_ntoseye"
crate-type = ["cdylib"]

[dependencies]
ntoseye_core = { package = "ntoseye", path = "..", default-features = false, features = ["python-extension"] }
pyo3 = { version = "0.29.0", features = ["extension-module", "abi3-py39"] }
